name: MCP Server Tests

on:
  push:
    branches: [ main, develop ]
    paths: ['mcp/**']
  pull_request:
    branches: [ main, develop ]
    paths: ['mcp/**']

jobs:
  mcp-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install MCP dependencies
      run: |
        cd mcp
        echo "Upgrading pip..."
        python -m pip install --upgrade pip
        echo "Installing dependencies from requirements.txt..."
        pip install --verbose --no-cache-dir -r requirements.txt
        echo "Installing additional test dependencies..."
        pip install --verbose --no-cache-dir pytest pytest-asyncio
        echo "Ensuring PyYAML is installed..."
        pip install --verbose --no-cache-dir PyYAML
        echo "Verifying installations..."
        pip list | grep -E "(neo4j|pydantic|pyyaml|aiohttp|pytest)"
        echo "Testing imports..."
        python -c "import yaml; print('yaml import OK')"
        python -c "import neo4j; print('neo4j import OK')"
        python -c "import pydantic; print('pydantic import OK')"
        python -c "import aiohttp; print('aiohttp import OK')"
        python -c "import pytest; print('pytest import OK')"
    
    - name: Test requirements
      run: |
        cd mcp
        python test_requirements.py
    
    - name: Test yaml
      run: |
        cd mcp
        python test_yaml.py
    
    - name: Test environment
      run: |
        cd mcp
        python test_environment.py
    
    - name: Test config
      run: |
        cd mcp
        python test_config.py
    
    - name: Test file structure
      run: |
        cd mcp
        python test_file_structure.py
    
    - name: Run MCP server tests
      run: |
        cd mcp
        python run_tests.py 