name: MCP Server Tests

on:
  push:
    branches: [ main, develop ]
    paths: ['mcp/**']
  pull_request:
    branches: [ main, develop ]
    paths: ['mcp/**']

jobs:
  mcp-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup uv
      uses: astral-sh/setup-uv@v1
      with:
        version: "latest"
    
    - name: Install dependencies
      run: |
        uv sync --all-extras
    
    - name: Run MCP server tests
      run: |
        cd mcp
        python run_tests.py 